spring.application.name=codequest-back
# H2データベースの接続設定
spring.datasource.url=jdbc:h2:mem:codequestdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2コンソール（ブラウザでDBを見るツール）を有効化
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 起動時にschema.sqlとdata.sqlを自動実行する設定
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true